name: AI Evaluation

on: [push, pull_request]

jobs:
  evalute:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout AI
        uses: actions/checkout@v2

      -
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      -
        name: Set up pip
        run: python -m pip install --upgrade pip

      -
        name: Prepare enviroment
        run: make install-venv

      -
        id: evaluation
        name: Run tournament
        run: make --silent evaluate-tournament-to-json 2>&1 | tee logs/.make-log

      -
        name: Store logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs/

      -
        id: results
        name: Load results
        run: echo "::set-output name=tournament_results::$(cat logs/.make-log | awk NF | tail -n1)"

      -
        name: Post results to comment
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            # Results
            * ```${{ steps.results.outputs.tournament_results }}```
