name: AI Evaluation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout AI
        uses: actions/checkout@v2

      -
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      -
        name: Set up pip
        run: python -m pip install --upgrade pip

      -
        name: Prepare enviroment
        run: make install-venv

      -
        id: evaluation
        name: Run tournament
        run: echo "::set-output name=tournament_results::$(make evaluate-tournament 2>&1)\n"

      -
        name: Post results to comment
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            # Results
            * ${{ join(steps.evaluation.outputs.*, '\n') }}
            * ${{ steps.evaluation.outputs.tournament_results }}
